version: '2'

volumes:
  # MySQL Data
  convenia-mysql-data:
    driver: local

  # Redis Data
  convenia-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: convenia-mysql
    volumes:
      - convenia-mysql-data:/var/lib/mysql
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=masterkey
      - MYSQL_DATABASE=convenia
      - MYSQL_USER=convenia
      - MYSQL_PASSWORD=masterkey

  # Redis
  cache:
    image: redis:4.0
    container_name: convenia-redis
    command: --appendonly yes
    volumes:
      - convenia-redis-data:/data
    ports:
      - "10002:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: convenia-app
    volumes:
      - .:/var/www/app
    ports:
      - "8005:8080"
    links:
      - mysql
      - cache